# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: false
cache:
  packages: true
  directories:
  - $HOME/.npm

r_packages: 
- blogdown
- tidyverse

before_install:
- npm install netlify-cli -g

before_script:
- Rscript -e 'blogdown::install_hugo()'

script:
- Rscript -e 'blogdown::build_site()'

deploy:
  provider: script
  script: netlify deploy -t $NETLIFYKEY
  skip_cleanup: true
